include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    FORCE_DOCKER_COMPOSE: 1
    SERVICES_TO_CHECK: ${CI_PROJECT_NAME}
