include:
  - project: 'redmic-project/gitlab-ci-templates'
    ref: master
    file: '/deployment.yml'

stages:
  - deploy

.deploy:
  variables:
    STACK: storage
    FORCE_DOCKER_COMPOSE: 1
    COMPOSE_FILE: docker-compose.yml
